services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant/storage:/qdrant/storage
  quokka-server:
    image: quokka-server:latest
    depends_on:
      - qdrant
    ports:
      - 8000:80
    environment:
      - qdrant_host=qdrant
      - qdrant_port=6333
      - qdrant_collection=poi
      - device=cpu
      - front_path="/quokka"
